version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://localhost:9000

  backend:
    build: ./server
    ports:
      - "9000:9000"
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000
      - MONGO_URL=mongodb://admin:pass@mongodb:27017/
      - PORT=9000
    depends_on:
      - mongodb

volumes:
  mongo_data: